### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by petecoop** [petecoop/phantasma#9]
Add cookie support, http://phantomjs.org/api/phantom/property/cookies.html

**Comment by jes-carr** [comment]
I didn't even notice the lack of cookies because I managed to run the whole automation with the same session. It worked much better than Nightmare, that I needed to log in again after each `run`, even when using cookies.

So thanks a lot for creating this. It makes complex scrapping delightful! I'll let you know if I find any issues down the line.

**Comment by petecoop** [comment]
Good to hear! I created the project because of my own issues with Nightmare, but I haven't actually had chance to put it to use on the project it was made for!

As for the cookie support - the idea is to be able to add your own or to start a session with some pre-loaded cookies.

If you have any issues or suggestions on how to make this project better, then feel free to open an issue

**Comment by inca** [comment]
Hats off, :gem: stuff you've got there, @petecoop, I guess every Node.js developer owes you a big fat can of thanks!
Sorry for off-topic question: do you plan on supporting/maintaining/evolving it? Do you use it yourself? How come you didn't put it to good use for your initial project?

**Comment by petecoop** [comment]
Glad you like it @inca, looks like a handful of developers are using it at the minute but hoping it'll take off because in my opinion it's a lot better than the alternatives.

I do plan on keeping it maintained. Still not using it in that project yet, it's just been delayed while I work/play on some other bits and pieces but will definitely be using it within a month or so
